FROM ghcr.io/dockhippie/php-apache:8.4-amd64@sha256:29a4ffc4f95958bea926f2a61d99a51fa332d5dba8b6c9663836aceb80bd84d8

VOLUME ["/var/lib/mywebsql"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=Samnan/MyWebSQL
ENV MYWEBSQL_VERSION=3.9

RUN curl -sSLo /tmp/mywebsql.zip https://github.com/Samnan/MyWebSQL/releases/download/v${MYWEBSQL_VERSION}/mywebsql.zip && \
  cd /tmp && \
  busybox unzip mywebsql.zip && \
  find mywebsql -type f -iname .DS_Store -delete && \
  rm -rf mywebsql/Docs mywebsql/index.html && \
  rsync -aP mywebsql/ /srv/www && \
  rm -rf __MACOSX mywebsql.zip mywebsql && \
  chown -R apache:apache /srv/www

COPY ./overlay /
