FROM ghcr.io/dockhippie/php-apache:8.4-arm64@sha256:ae35926913a383d99cd125b6d0b4a1b14d10f4a997526b8b15901e053a42b999

VOLUME ["/var/lib/mywebsql"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk add php${PHP_PACKAGE_VERSION}-ldap sqlite git && \
  rm -rf /var/cache/apk/*

ENV PHP_COMPOSER_INSTALL=false

# renovate: datasource=github-releases depName=Samnan/MyWebSQL
ENV MYWEBSQL_VERSION=3.9

RUN curl -sSLo /tmp/mywebsql.zip https://github.com/Samnan/MyWebSQL/releases/download/v${MYWEBSQL_VERSION}/mywebsql.zip && \
  cd /tmp && \
  busybox unzip mywebsql.zip && \
  find mywebsql -type f -iname .DS_Store -delete && \
  rm -rf mywebsql/Docs mywebsql/index.html && \
  rsync -aP mywebsql/ /srv/www && \
  rm -rf __MACOSX mywebsql.zip mywebsql && \
  chown -R apache:apache /srv/www

COPY ./overlay /

RUN find /etc/container.d /etc/entrypoint.d -type f -name \*.sh -exec sed -i 's/\r$//' {} +; \
  chmod +x /etc/container.d/*.sh /etc/entrypoint.d/*.sh
