#!/bin/bash

declare -x MYWEBSQL_AUTH_TYPE
declare -x MYWEBSQL_AUTH_SERVER
declare -x MYWEBSQL_AUTH_LOGIN
declare -x MYWEBSQL_AUTH_PASSWORD
declare -x MYWEBSQL_BACKUP_FILENAME_FORMAT
declare -x MYWEBSQL_BACKUP_DATE_FORMAT
declare -x MYWEBSQL_TRACE_MESSAGES
declare -x MYWEBSQL_TRACE_FILEPATH
declare -x MYWEBSQL_LOG_MESSAGES
declare -x MYWEBSQL_MAX_RECORD_TO_DISPLAY
declare -x MYWEBSQL_MAX_TEXT_LENGTH_DISPLAY
declare -x MYWEBSQL_HOTKEYS_ENABLED
declare -x MYWEBSQL_DEFAULT_EDITOR
declare -x MYWEBSQL_DEFAULT_THEME
declare -x MYWEBSQL_DEFAULT_LANGUAGE
declare -x MYWEBSQL_ALLOW_CUSTOM_SERVERS
declare -x MYWEBSQL_ALLOW_CUSTOM_SERVER_TYPES
declare -x MYWEBSQL_SERVER_LIST

[[ -z "${MYWEBSQL_AUTH_TYPE}" ]] && MYWEBSQL_AUTH_TYPE="LOGIN"
[[ -z "${MYWEBSQL_AUTH_SERVER}" ]] && MYWEBSQL_AUTH_SERVER="mysql|mysql5"
[[ -z "${MYWEBSQL_AUTH_LOGIN}" ]] && MYWEBSQL_AUTH_LOGIN="test"
[[ -z "${MYWEBSQL_AUTH_PASSWORD}" ]] && MYWEBSQL_AUTH_PASSWORD="test"
[[ -z "${MYWEBSQL_BACKUP_FILENAME_FORMAT}" ]] && MYWEBSQL_BACKUP_FILENAME_FORMAT="<db>-<date><ext>"
[[ -z "${MYWEBSQL_BACKUP_DATE_FORMAT}" ]] && MYWEBSQL_BACKUP_DATE_FORMAT="Ymd-His"
[[ -z "${MYWEBSQL_TRACE_MESSAGES}" ]] && MYWEBSQL_TRACE_MESSAGES="false"
[[ -z "${MYWEBSQL_LOG_MESSAGES}" ]] && MYWEBSQL_LOG_MESSAGES="false"
[[ -z "${MYWEBSQL_MAX_RECORD_TO_DISPLAY}" ]] && MYWEBSQL_MAX_RECORD_TO_DISPLAY="100"
[[ -z "${MYWEBSQL_MAX_TEXT_LENGTH_DISPLAY}" ]] && MYWEBSQL_MAX_TEXT_LENGTH_DISPLAY="80"
[[ -z "${MYWEBSQL_HOTKEYS_ENABLED}" ]] && MYWEBSQL_HOTKEYS_ENABLED="true"
[[ -z "${MYWEBSQL_DEFAULT_EDITOR}" ]] && MYWEBSQL_DEFAULT_EDITOR="codemirror"
[[ -z "${MYWEBSQL_DEFAULT_THEME}" ]] && MYWEBSQL_DEFAULT_THEME="default"
[[ -z "${MYWEBSQL_DEFAULT_LANGUAGE}" ]] && MYWEBSQL_DEFAULT_LANGUAGE="en"
[[ -z "${MYWEBSQL_ALLOW_CUSTOM_SERVERS}" ]] && MYWEBSQL_ALLOW_CUSTOM_SERVERS="false"
[[ -z "${MYWEBSQL_ALLOW_CUSTOM_SERVER_TYPES}" ]] && MYWEBSQL_ALLOW_CUSTOM_SERVER_TYPES="mysql,pgsql"
[[ -z "${MYWEBSQL_SERVER_LIST}" ]] && MYWEBSQL_SERVER_LIST="mysqli:localhost"

/usr/bin/templater -d -p mywebsql \
  -o /srv/www/config/auth.php \
  /etc/templates/auth.php.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p mywebsql \
  -o /srv/www/config/backups.php \
  /etc/templates/backups.php.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p mywebsql \
  -o /srv/www/config/config.php \
  /etc/templates/config.php.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p mywebsql \
  -o /srv/www/config/database.php \
  /etc/templates/database.php.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi

/usr/bin/templater -d -p mywebsql \
  -o /srv/www/config/servers.php \
  /etc/templates/servers.php.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
fi
